using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class PauseButton : MonoBehaviour
{

    public GameObject pauseUI;

    public void QuiteGame()
    {
        SceneManager.LoadScene("MenuGame");
    }

    public void Restart()
    {
        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    }

    public void PauseUI()
    {
        pauseUI.SetActive(true);
    }

    public void BackPauseUI()
    {
        pauseUI.SetActive(false);
    }
}
